---
title: "Memory benchmark of NApy package against state-of-the-art libraries on simulated data"
author: Fabian Woller, Lis Arend
date: "2024-09-27"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## ----- Load required libraries -----
required_packages <- c("data.table", "ggplot2", "dplyr", "patchwork", "RColorBrewer", "patchwork", "ggpubr")
for(package in required_packages){
  if(!require(package,character.only = TRUE, quietly = TRUE)) install.packages(package, dependencies = TRUE, quietly = TRUE)
  library(package, character.only = TRUE, quietly = TRUE)
}

## ----- Colors -----

library_colors <- c("NApy" = "#5b87ab", "SciPy" = "#018571", "SciPy - Python Loop" = "#80CDC1" , "pandas" = "#C01C8B", "Pingouin - Python Loop" = "#B2182B", "Pingouin" = "#F4A582","pandas - Python Loop" = "#F1B6DA", "NApy with Numba" = "#203f58", "NApy with C++" = "#acbed2")

## ----- Methods Sorting -----

method_sorting <-  c("Pearson", "Spearman", "t-test", "Mann-Whitney U", "ANOVA", "Kruskal-Wallis", "Chi-squared")
library_sorting <- c("NApy", "Pingouin", "SciPy", "pandas", "SciPy - Python Loop", "pandas - Python Loop")
ncol <- 4

## ----- Paths -----
out_dir <- "../plots/"


## ----- Theme -----
theme_new <- theme(legend.position = "bottom", axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), axis.title.x = element_text(size = 12), axis.title.y = element_text(size = 12), legend.text = element_text(size = 12), legend.title = element_text(size = 12), strip.text = element_text(size = 12), strip.background = element_rect(fill = "white"))

## ----- Helper Function -----

make_units_consistent <- function(dt){
  dt <- dt %>% mutate(
    size = as.numeric(gsub("[^0-9.]", "", memory)),
    unit = gsub("[0-9.]", "", memory)
  )
  
  dt$memory <- NULL
  setnames(dt, "size", "memory")
  
  ## Transform Units
  
  # if unit is GB -> multiple by 1000
  # if unit is KB -< divide by 1000
  
  dt <- dt %>% mutate(
    memory = case_when(
      unit == "MB" ~ memory / 1000,
      unit == "KB" ~ memory / 1000000,
      TRUE ~ memory
    )
  )
  
  dt$unit <- NULL
  return(dt)
}

read_allocated_memory_files <- function(file_path){
  dt <- read.csv(file_path)
  dt <- as.data.table(dt)
  
  ## ----- Make memory units consistent -----
  dt <- make_units_consistent(dt)
  
  ## ----- Summarizing Runs -----
  summ_dt <- dt %>% group_by(samples, features, threads, na_ratio, library, method) %>% summarize(mean_mem = mean(memory, na.rm = TRUE), sd_mem = sd(memory, na.rm = TRUE))
  return(summ_dt)
}

read_peak_memory_files <- function(file_path){
  dt <- read.csv(file_path, sep="\t", row.names = 1)
  dt <- as.data.table(dt)
  
  colnames(dt) <- c("run", "threads", "library", "method", "memory", "samples", "features", "na_ratio")
  
  ## ----- Summarizing Runs -----
  summ_dt <- dt %>% group_by(samples, features, threads, na_ratio, method, library) %>% summarize(mean_mem = mean(memory, na.rm = TRUE), sd_mem = sd(memory, na.rm = TRUE))
  return(summ_dt)
}

rename_data <- function(dt){
  dt$threads <- as.factor(dt$threads)
  dt$features <- as.factor(dt$features)
  dt$samples <- as.factor(dt$samples)
  # Rename libraries
  dt$library <- gsub("nanpy", "NApy", dt$library)
  dt$library <- gsub("napy_cpp", "NApy with C++", dt$library)
  dt$library <- gsub("napy_numba", "NApy with Numba", dt$library)
  dt$library <- gsub("numba", "NApy with Numba", dt$library)
  dt$library[dt$library == "scipy_par"] <- "SciPy - Python Loop"
  dt$library <- gsub("scipy", "SciPy", dt$library)
  dt$library <- gsub("pingouin", "Pingouin", dt$library)
  dt$library[dt$library == "SciPypar"] <- "SciPy - Python Loop"
  dt$library[dt$library == "pandas_par"] <- "pandas - Python Loop"
  dt$library[dt$library == "pandaspar"] <- "pandas - Python Loop"
  dt$library[dt$library == "Pingouinpar"] <- "Pingouin - Python Loop"
  # Rename methods
  dt$method <- gsub("pearson", "Pearson", dt$method)
  dt$method <- gsub("ttest", "t-test", dt$method)
  dt$method <- gsub("anova", "ANOVA", dt$method)
  dt$method <- gsub("chi2", "Chi-squared", dt$method)
  dt$method <- gsub("spearman", "Spearman", dt$method)
  dt$method <- gsub("mwu", "Mann-Whitney U", dt$method)
  dt$method <- gsub("kruskal_wallis", "Kruskal-Wallis", dt$method)
  dt$method <- gsub("kw", "Kruskal-Wallis", dt$method)
  dt$method <- gsub("kruskal", "Kruskal-Wallis", dt$method)
  dt$method <- factor(dt$method, levels = method_sorting)
  return(dt)
}  
```

# Allocated Memory

## Reading Files and Preprocess Data

```{r}
## Memory 
input_dir <- "../results/memory/"
alloc_memory_dt <- NULL

for(file in list.files(input_dir, pattern = "_updated")){
  dt <- read_allocated_memory_files(paste0(input_dir, file))
  dt$file <- file
  if(is.null(alloc_memory_dt)){
    alloc_memory_dt <- dt
  } else {
    alloc_memory_dt <- rbind(alloc_memory_dt, dt)
  }
}

alloc_memory_dt <- rename_data(alloc_memory_dt)

```

## Final Allocated Memory Table

```{r}
dt <- alloc_memory_dt
dt$samples <- NULL
dt$features <- NULL
dt$file <- NULL
dt$na_ratio <- NULL


dt$memory <- paste0(round(dt$mean_mem, 3), " (", round(dt$sd_mem, 3), ")")
dt$mean_mem <- NULL
dt$sd_mem <- NULL

dt <- dcast(as.data.table(dt), library + threads ~ method, value.var = "memory")

dt

write.csv(dt, paste0(out_dir, "peak_allocated_memory.csv"))
```


# Peak-Memory Consumption

```{r}
## Memory 
input_dir <- "../results/memory/"
peak_memory_dt <- NULL

for(file in list.files(input_dir, pattern = "results.tsv")){
  dt <- read_peak_memory_files(paste0(input_dir, file))
  dt$file <- file
  if(is.null(peak_memory_dt)){
    peak_memory_dt <- dt
  } else {
    peak_memory_dt <- rbind(peak_memory_dt, dt)
  }
}

peak_memory_dt <- rename_data(peak_memory_dt)
```

Plot Peak Memory Only for NApy C++ and Numba

```{r}
peak_memory_dt_napy <- peak_memory_dt[peak_memory_dt$library %in% c("NApy with C++", "NApy with Numba"),]

tmp <- peak_memory_dt_napy %>% mutate(method = recode_factor(method, 
                                              "Pearson"="Pearson", 
                                              "Spearman"="Spearman",
                                              "t-test" = "italic(t)~-Test",
                                              "Mann-Whitney U" = "Mann-Whitney~italic(U)",
                                              "ANOVA" = "ANOVA",
                                              "Kruskal-Wallis" = "Kruskal-Wallis",
                                              "Chi-squared" = "chi^2~-Test"))

tmp$method <- factor(tmp$method, levels = c("Pearson", "italic(t)~-Test", "ANOVA", "chi^2~-Test", "Spearman", "Mann-Whitney~italic(U)","Kruskal-Wallis"))


memory_c_numba_plot <- ggplot(tmp[tmp$samples == 1000 & tmp$features == 1000,], aes(x = as.factor(threads), y = mean_mem, fill = library)) + 
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) + geom_errorbar(aes(ymin = mean_mem - sd_mem, ymax = mean_mem + sd_mem), width = 0.2, position = position_dodge(width = 0.9)) +
  facet_wrap(~method, ncol = 4, label = "label_parsed", scales = "free_y") + 
  theme_bw() + scale_fill_manual(values = library_colors, labels = c("C++", "Numba")) + labs(x = "Number of Threads", y = "Mean Peak Resident Memory (MB)", fill = "NApy Version") + theme_new + theme(strip.background = element_rect(fill = "white"), legend.position = "top")

ggsave(paste0(out_dir, "peak_memory_napy_numba_c++.png"), width = 10, height = 8, dpi = 300)
```


Wrap with runtime plot together:

```{r}
wrap_elements(runtime_c_numba_plot) / wrap_elements(memory_c_numba_plot) + plot_annotation(tag_levels = 'A') + plot_layout(heights = c(1, 1.5), axes = "keep") & theme(legend.position = "top", plot.tag = element_text(size = 20, face = "bold")) 

ggsave(paste0(out_dir, "runtime_memory_napy_numba_c++.png"), width = 9, height = 11, dpi = 300)

```


Update table with default NApy implementation

```{r}
## ----- For parametric libraries -> make numba -> NApy -----
new_napy_param <- peak_memory_dt_napy[peak_memory_dt_napy$method %in% c("Pearson", "Chi-squared", "ANOVA", "t-test") & peak_memory_dt_napy$library == "NApy with Numba",]
new_napy_param$library <- "NApy"
new_napy_non_param <- peak_memory_dt_napy[peak_memory_dt_napy$method %in% c("Spearman", "Kruskal-Wallis", "Mann-Whitney U") & peak_memory_dt_napymem$library == "NApy with C++",]
new_napy_non_param$library <- "NApy"

peak_memory_dt <- peak_memory_dt[!peak_memory_dt$library %in% c("NApy with C++", "NApy with Numba"),]
peak_memory_dt <- rbind(new_napy_param, new_napy_non_param, peak_memory_dt)

peak_memory_dt$method <- factor(peak_memory_dt$method, levels = method_sorting)
peak_memory_dt$library <- factor(peak_memory_dt$library, levels = library_sorting)
```

```{r}
tmp <- peak_memory_dt %>% mutate(method = recode_factor(method, 
                                              "Pearson"="Pearson", 
                                              "Spearman"="Spearman",
                                              "t-test" = "italic(t)~-Test",
                                              "Mann-Whitney U" = "Mann-Whitney~italic(U)",
                                              "ANOVA" = "ANOVA",
                                              "Kruskal-Wallis" = "Kruskal-Wallis",
                                              "Chi-squared" = "chi^2~-Test"))


ggplot(tmp, aes(x = as.factor(threads), y = mean_mem, fill = library)) + geom_bar(stat="identity", position = position_dodge(width = 0.9)) + geom_errorbar(aes(ymin = mean_mem - sd_mem, ymax = mean_mem + sd_mem), width = 0.2, position = position_dodge(width = 0.9)) +
  facet_wrap(~method, scales="free_y", ncol = 7, label = "label_parsed") + theme_bw() + labs(x = "Threads", y= "Mean Peak Resident Memory (MB)", fill = "Library") + scale_fill_manual(values = library_colors) + theme(strip.background = element_rect(fill = "white"), legend.position = "bottom") + guides(fill = guide_legend(nrow = 1))

ggsave(paste0(out_dir, "peak_memory_napy_competitors.png"), width = 12, height = 4, dpi = 300)

```


# Hardware Comparison


```{r}
## Memory 
input_dir <- "../results/memory/"
peak_memory_fau_dt <- NULL

for(file in list.files(input_dir, pattern = "results_fau.tsv")){
  dt <- read_peak_memory_files(paste0(input_dir, file))
  dt$file <- file
  if(is.null(peak_memory_fau_dt)){
    peak_memory_fau_dt <- dt
  } else {
    peak_memory_fau_dt <- rbind(peak_memory_fau_dt, dt)
  }
}

peak_memory_fau_dt <- rename_data(peak_memory_fau_dt)
```

Plot Peak Memory

```{r}
## NApy C++ vs numba
peak_memory_fau_dt_napy <- peak_memory_fau_dt[peak_memory_fau_dt$library %in% c("NApy with C++", "NApy with Numba"),]

tmp <- peak_memory_fau_dt_napy %>% mutate(method = recode_factor(method, 
                                              "Pearson"="Pearson", 
                                              "Spearman"="Spearman",
                                              "t-test" = "italic(t)~-Test",
                                              "Mann-Whitney U" = "Mann-Whitney~italic(U)",
                                              "ANOVA" = "ANOVA",
                                              "Kruskal-Wallis" = "Kruskal-Wallis",
                                              "Chi-squared" = "chi^2~-Test"))

tmp$method <- factor(tmp$method, levels = c("Pearson", "italic(t)~-Test", "ANOVA", "chi^2~-Test", "Spearman", "Mann-Whitney~italic(U)","Kruskal-Wallis"))


memory_fau_c_numba_plot <- ggplot(tmp[tmp$samples == 1000 & tmp$features == 1000,], aes(x = as.factor(threads), y = mean_mem, fill = library)) + 
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) + geom_errorbar(aes(ymin = mean_mem - sd_mem, ymax = mean_mem + sd_mem), width = 0.2, position = position_dodge(width = 0.9)) +
  facet_wrap(~method, ncol = 4, label = "label_parsed", scales = "free_y") + 
  theme_bw() + scale_fill_manual(values = library_colors, labels = c("C++", "Numba")) + labs(x = "Number of Threads", y = "Mean Peak Resident Memory (MB)", fill = "NApy Version") + theme_new + theme(strip.background = element_rect(fill = "white"), legend.position = "top")

ggsave(paste0(out_dir, "peak_memory_fau_napy_numba_c++.png"), width = 10, height = 8, dpi = 300)
```


Wrap with runtime plot together:

```{r}
wrap_elements(runtime_fau_c_numba_plot) / wrap_elements(memory_fau_c_numba_plot) + plot_annotation(tag_levels = 'A') + plot_layout(heights = c(1, 1.5), axes = "keep") & theme(legend.position = "top", plot.tag = element_text(size = 20, face = "bold")) 

ggsave(paste0(out_dir, "runtime_memory_fau_napy_numba_c++.png"), width = 9, height = 11, dpi = 300)

```