---
title: "Robustness Analysis of Missingness Mechanisms"
author: Fabian Woller, Lis Arend
date: "2024-09-27"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## ----- Load required libraries -----
required_packages <- c("data.table", "ggplot2", "dplyr", "patchwork", "RColorBrewer", "patchwork", "ggpubr")
for(package in required_packages){
  if(!require(package,character.only = TRUE, quietly = TRUE)) install.packages(package, dependencies = TRUE, quietly = TRUE)
  library(package, character.only = TRUE, quietly = TRUE)
}

## ----- Methods Sorting -----

method_sorting <-  c("Pearson", "Spearman", "t-test", "Mann-Whitney-U", "ANOVA", "Kruskal-Wallis", "Chi-squared")

## ----- Paths -----
input_dir <- "../../robustness/"
out_dir <- "../plots/"


## ----- Theme -----
theme_new <- theme(legend.position = "bottom", axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14), legend.text = element_text(size = 12), legend.title = element_text(size = 14), strip.text = element_text(size = 14), strip.background = element_rect(fill = "white"))

rename_data <- function(dt){
  # Rename methods
  dt$method <- gsub("pearson", "Pearson", dt$method)
  dt$method <- gsub("ttest", "t-test", dt$method)
  dt$method <- gsub("anova", "ANOVA", dt$method)
  dt$method <- gsub("chi2", "Chi-squared", dt$method)
  dt$method <- gsub("spearman", "Spearman", dt$method)
  dt$method <- gsub("mwu", "Mann-Whitney-U", dt$method)
  dt$method <- gsub("kruskal", "Kruskal-Wallis", dt$method)
  dt$method <- factor(dt$method, levels = method_sorting)
  
  return(dt)
}
```



# Robustness Continuous - Continuous

## Reading Files and Preprocess Data

```{r}
robust_dt <- NULL
for(file in list.files(input_dir, pattern = "stability_analysis")){
  dt <- fread(paste0(input_dir, file))
  if(is.null(runtime_dt)){
    robust_dt <- dt
  } else {
    robust_dt <- rbind(robust_dt, dt)
  }
}

robust_dt$method <- robust_dt$test
robust_dt <- rename_data(robust_dt)
```



## Plot Data

P-value 

```{r}
plot_pval <- ggplot(robust_dt, aes( x= as.factor(na_ratio), y = -log10(pvalue), fill = mechanism)) + geom_violin(width = 0.7, alpha = 0.5) + geom_boxplot(width = 0.2, position = position_dodge(width=0.7)) + theme_bw() + theme_new + facet_wrap(~method, scales="free_y", ncol = 1) +
  labs(x = "Missing Value Ratio", fill = "Missingness Mechanism") + ylab(expression(-log[10](italic(P)-value))) + theme(legend.position = "top")
```

Effect Size

```{r}
plot_effect_size <- ggplot(robust_dt, aes( x= as.factor(na_ratio), y = effect_size, fill = mechanism)) + geom_violin(width = 0.7, alpha = 0.5) + geom_boxplot(width = 0.2, position = position_dodge(width=0.7)) + theme_bw() + theme_new + facet_wrap(~method, scales="free_y", ncol = 1) +
  labs(x = "Missing Value Ratio", fill = "Missingness Mechanism") + ylab("Effect Size") + theme(legend.position = "top")
```

Both Plots Together

```{r}
plot_pval + plot_effect_size + plot_layout(ncol = 2, guides = "collect", axes = "collect") + plot_annotation(tag_levels = "A") & theme(legend.position = 'bottom', plot.tag = element_text(size = 20, face = "bold")) 
ggsave(paste0(out_dir, "robustness_missingness.png"), width = 12, height = 20)
```

